# Generated by Django 4.2.16 on 2024-10-02 10:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(choices=[('Anti Wrinkle - Consultation', 'Anti Wrinkle - Consultation'), ('Anti Wrinkle - 1 Area', 'Anti Wrinkle - 1 Area'), ('Anti Wrinkle - 2 Areas', 'Anti Wrinkle - 2 Areas'), ('Anti Wrinkle - 3 Areas', 'Anti Wrinkle - 3 Areas'), ('Dermal Filler - 0.5ml Lip Filler', 'Dermal Filler - 0.5ml Lip Filler'), ('Dermal Filler - 1ml Lip Filler', 'Dermal Filler - 1ml Lip Filler'), ('Dermal Filler - Lip Dissolving', 'Dermal Filler - Lip Dissolving'), ('Skin Booster - Seventy Hyal / S-DNA', 'Skin Booster - Seventy Hyal / S-DNA'), ('Skin Booster - Profilo', 'Skin Booster - Profilo'), ('Skin Booster - Lumi Eyes', 'Skin Booster - Lumi Eyes'), ('Facials - Basic Dermaplane', 'Facials - Basic Dermaplane'), ('Facials - Luxury Dermaplane', 'Facials - Luxury Dermaplane'), ('Facials - MYSA Signature Facial', 'Facials - MYSA Signature Facial'), ('Lemon Bottle - Consultation', 'Lemon Bottle - Consultation'), ('Lemon Bottle - Small Area (Chin, Jowls...)', 'Lemon Bottle - Small Area (Chin, Jowls...)'), ('Lemon Bottle - Large Area (Tummy, Arms...)', 'Lemon Bottle - Large Area (Tummy, Arms...)'), ('Vitamin B12 - 1 Injection', 'Vitamin B12 - 1 Injection'), ('Vitamin B12 - Course of 5', 'Vitamin B12 - Course of 5')], default='Anti Wrinkle', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('9AM', '9AM'), ('9:30AM', '9:30AM'), ('10AM', '10AM'), ('10:30AM', '10:30AM'), ('11AM', '11AM'), ('11:30AM', '11:30AM'), ('12PM', '12PM'), ('2PM', '2PM'), ('2:30PM', '2:30PM'), ('3PM', '3PM'), ('3:30PM', '3:30PM'), ('4PM', '4PM'), ('4:30PM', '4:30PM'), ('5PM', '5PM')], default='9AM', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
